import type { AiAutomationDefinition } from "@/types/AiAutomation";

export const aiAutomationDefinitions: AiAutomationDefinition[] = [
  { id: "speech-to-text", title: "Chuyển giọng nói thành văn bản", shortTitle: "Speech → Text", description: "Nhận diện lời thoại, chia đoạn và tạo timestamp để dùng cho dịch, subtitle và dựng cảnh.", mode: "auto-translate", requiredCapabilities: ["speech"], optionalCapabilities: ["llm"], pipeline: ["Tách audio", "Speech recognition", "Timestamp", "Làm sạch transcript"] },
  { id: "translate-dub", title: "Tự động dịch & thuyết minh", shortTitle: "Dịch + Voice", description: "STT → dịch ngữ cảnh → tạo voice mới → đồng bộ với timeline gốc.", mode: "auto-translate", requiredCapabilities: ["speech", "llm", "voice"], optionalCapabilities: ["subtitle"], pipeline: ["STT", "Dịch", "TTS / Voice clone", "Audio mix"] },
  { id: "smart-subtitle", title: "Phụ đề tự động", shortTitle: "Auto Subtitle", description: "Tạo phụ đề có timestamp, chia câu thông minh và sẵn sàng xuất SRT/VTT hoặc burn-in.", mode: "auto-translate", requiredCapabilities: ["speech", "subtitle"], optionalCapabilities: ["llm"], pipeline: ["Transcript", "Sentence split", "Timing", "Subtitle style"] },
  { id: "voice-to-visual", title: "Tạo ảnh khớp với lời thoại", shortTitle: "Voice → Visual", description: "Phân tích từng câu thoại, sinh prompt theo scene và tạo ảnh/b-roll đồng bộ nội dung.", mode: "auto-remix", requiredCapabilities: ["llm", "image"], optionalCapabilities: ["speech", "object-detection", "face-analysis"], pipeline: ["Transcript", "Scene intent", "Prompt", "Image/B-roll", "Timeline match"] },
  { id: "idea-to-video", title: "Tự động tạo video từ ý tưởng", shortTitle: "Idea → Video", description: "Biến ý tưởng thành kịch bản, storyboard, prompt, scene video, voice và subtitle theo pipeline thống nhất.", mode: "auto-magic", requiredCapabilities: ["llm", "video"], optionalCapabilities: ["image", "voice", "subtitle"], pipeline: ["Ý tưởng", "Kịch bản", "Storyboard", "Visual", "Voice", "Render"] },
  { id: "auto-remix-pipeline", title: "Auto Remix AI Pipeline", shortTitle: "Remix Pipeline", description: "Chuỗi tự động đầy đủ cho video đầu vào: phân tích → viết lại → visual → voice → subtitle → xuất bản.", mode: "auto-remix", requiredCapabilities: ["llm", "speech"], optionalCapabilities: ["image", "video", "voice", "subtitle", "ocr", "scene-detection"], pipeline: ["Analyze", "Rewrite", "Visual", "Voice", "Subtitle", "QC", "Export"] }
];
